### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by burcehan** [jik876/hifi-gan#14] opened 2020-11-17 15:31 UTC
Hi,thanks for your work,
I only found the pretrained models of generator, is there any pretrained models of discriminator?
Thanks!

**Comment by SanjaESC** [comment] 2020-11-17 15:42
just some issues bellow...

https://github.com/jik876/hifi-gan/issues/5#issue-731893258

**Comment by jik876** [comment] 2020-11-18 01:11
Thanks for your interest.
We will update the pretrained model files soon.

**Comment by jik876** [comment] 2020-11-30 04:25
Duplicate of #5

**Comment by jik876** [comment] 2021-01-11 02:37
I close this as there are no recent updates. Please reopen if you need additional comments.

**Closed by jik876** 2021-01-11 02:37 UTC
