### ISSUE TITLE
break point problem

### ISSUE THREAD

**Issue by hdmjdp** [jik876/hifi-gan#26] opened 2020-12-09 03:05 UTC
![图片](https://user-images.githubusercontent.com/26831425/101568741-2636a280-3a0e-11eb-826f-cec47ecd9f37.png)
the spec has beak point, what do you think the reason of this problem is? I have enlarged the receptive: [1,3,5]-->[1,3,5,7], but the problem still exists.

And why your leak_relu_scope=0.1 instead of 0.2?

**Comment by jik876** [comment] 2020-12-10 03:48
I have not observed this issue in our experiments.
Have you made any changes to the implementation we provide?

We observed that the modified leaky relu slope improves the quality more stably.

**Comment by hdmjdp** [comment] 2020-12-10 04:41
@jik876 the break point existed in the male data, but not in the female data.

**Comment by jik876** [comment] 2020-12-14 03:29
We didn't observe such a phenomenon in our experiments including the multi-speaker case.
I don't know the quality of the dataset, but looking at the image you uploaded, it seems that training steps may be too early.
It would also be nice to check what has changed in the implementation we provided.

**Comment by hdmjdp** [comment] 2020-12-15 04:38
@jik876 thanks， how can I train faster? Now the speed of training is too slow. 1.2s/b

**Comment by CookiePPP** [comment] 2020-12-15 04:39
@hdmjdp 
Can you explain the problem or maybe upload an audio sample?
I don't really understand what is wrong when I look at the spectrogram.

**Comment by hdmjdp** [comment] 2020-12-15 05:02
@CookiePPP  like this
![图片](https://user-images.githubusercontent.com/26831425/102173356-cc365100-3ed5-11eb-9ec5-c7c316c00aeb.png)



[eval-1380000-12_generated_e2e.wav.zip](https://github.com/jik876/hifi-gan/files/5693480/eval-1380000-12_generated_e2e.wav.zip)

**Comment by hdmjdp** [comment] 2020-12-15 05:04
@CookiePPP Another question, whether GLOW-TTS is better than tacotron2?

**Comment by jik876** [comment] 2020-12-16 02:23
@hdmjdp 

In our experiments, it took between 0.4 and 0.45 seconds per step using 2 V100 GPUs.
It would be nice to check where the time is consuming.
To accelerate training, you will have to take a trade-off in quality. 
Removing the 2nd and 3rd discriminators of MSD would be a good attempt to accelerate training as it doesn't lead to significant quality degradation.

**Comment by hdmjdp** [comment] 2020-12-16 03:21
@jik876 I used the dis like this because of 48k. In your opinion, the DiscriminatorP(2) is more important?
self.discriminators = nn.ModuleList([
            #DiscriminatorP(2),
            DiscriminatorP(3),
            DiscriminatorP(5),
            DiscriminatorP(7),
            DiscriminatorP(11),
            DiscriminatorP(17),
            DiscriminatorP(23),
            #DiscriminatorP(37),
        ])

**Comment by hdmjdp** [comment] 2020-12-16 03:24
@jik876 what is your advice about discriminators for 48k model?

**Comment by jik876** [comment] 2020-12-16 09:13
@hdmjdp 

Since 48kHz will have a longer pattern than 22kHz for same duration, it seems reasonable to enlarge the period of the discriminator and the receptive field of the generator, but this should be confirmed through experimentation.
#8 will be useful information for you.
Regardless of the sample rate, I think the discriminator with period 2 is important in your configuration. Since your configuration makes the discriminator sparsely handles data with periods of multiples of 2, it would be nice to add a discriminator with period 2 or period 4.

**Comment by hdmjdp** [comment] 2020-12-16 09:19
@jik876 yes，I will try your advice. I encouner a bad case: there is machine soud(a line) in the 4k frequency as below.  this is breathing part. I try to solve it, Can you give some advice, thanks.

![图片](https://user-images.githubusercontent.com/26831425/102329179-0a5d6e80-3fc3-11eb-8aea-4c97cb258ef7.png)

**Comment by jik876** [comment] 2020-12-18 07:47
I would like to recommend adding the discriminator with period 2 first.

**Comment by jik876** [comment] 2021-04-25 08:00
I close this as there are no recent updates. Please reopen if you need additional comments.

**Closed as completed by jik876** 2021-04-25 08:00 UTC
